package com.example.employee_demo.controller;

import com.example.employee_demo.models.EmployeeModel;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import com.example.employee_demo.repository.EmployeeRepository;

@Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class EmployeeController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private EmployeeRepository employeeRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewUser (@RequestBody EmployeeModel employee) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        employeeRepository.save(employee);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<EmployeeModel> getAllUsers() {
        // This returns a JSON or XML with the users
        return employeeRepository.findAll();
    }
}

