package com.example.employee_demo.service;

import com.example.employee_demo.models.EmployeeModel;
import com.example.employee_demo.repository.EmployeeRepository;
import org.springframework.beans.factory.annotation.Autowired;

import java.util.ArrayList;
import java.util.List;

public class EmployeeService {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private EmployeeRepository employeeRepository;

    public String save(EmployeeModel employee){
        employeeRepository.save(employee);
        return "Saved";
    }

    public Iterable<EmployeeModel> findAll(){
        Iterable<EmployeeModel> all = new ArrayList<>();
        all = (List<EmployeeModel>) employeeRepository.findAll();
        return all;
    }
}
